<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/edtf-data-type.css', 'EdtfDataType'));

if (getenv('APPLICATION_ENV') === 'development') {

    $url = 'http://localhost:8081/edtf-data-type.min.js'; 

    if(!$fp = curl_init($url)) {
        $this->headScript()->appendFile($url);
        $this->headScript()->appendFile('http://localhost:35729/livereload.js');
    } else { 
        $this->headScript()->appendFile($this->assetUrl('js/edtf-data-type.js', 'EdtfDataType'));
     }
} else {
    $this->headScript()->appendFile($this->assetUrl('js/edtf-data-type.min.js', 'EdtfDataType'));
}
$formText = clone($this->plugin('formText'));
$formText->addTranslatableAttribute('aria-label');
?>
<div class="edtf">
    <div class="error invalid-value"
        data-invalid-message="<?php echo $this->escapeHtml($this->translate('Invalid value: %s')); ?>"
        data-custom-validity="<?php echo $this->escapeHtml($this->translate('Value must be an EDTF datetime')); ?>">
    </div>
    <div class="edtf-datetime-inputs">
        <div class="edtf-inputs">
            <?php echo $formText($element->getValueElement()); ?>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            EdtfDataType.listen();
        });
    </script>
</div>
